### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by magriggs** [MikeJuniperhill/QuantLib.AutoCallable.Memory.Coupon.Note#1]
Hi, I would like to use your example code in another example/learning project that will be shared publicly. Please could you add an open source license?

**Comment by MikeJuniperhill** [comment]
What license? Just go ahead.
-Mike

ti 25. lokak. 2022 klo 6.06 magriggs ***@***.***) kirjoitti:

**Comment by magriggs** [comment]
Thanks

**Comment by MikeJuniperhill** [comment]
Get paid for answering short surveys. Download Google Opinion Rewards now:
https://googleopinionrewards.page.link/share
